version: "2.2"
services:
  jgw:
    image: intersystemsdc/jgw:2022.3
#    environment:
#      - JVMARGS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 55555:55555
#      - 5005:5005
